#!/usr/bin/env python3
"""Assemble a deployable STATIC tree — no application server required.

The browser port needs no server-side logic: it is files plus three response
headers.  This collects exactly what a visitor fetches, resolves the symlinks
the dev tree uses, drops the dev-only harnesses, and writes the host config
alongside, so a deploy is one ``rsync``.

    scripts/wasm/stage-static.py --build 1A543a --out /tmp/deploy
    rsync -a --delete /tmp/deploy/ user@host:/var/www/iphone/

What the host MUST do (all three are checked into the generated config):

1. **COOP/COEP.**  The emulator runs on pthreads, which needs
   ``SharedArrayBuffer``, which browsers grant only to a cross-origin-isolated
   page.  Without these headers the page fails at startup.
2. **HTTPS.**  ``SharedArrayBuffer`` and service workers both require a secure
   context.  ``localhost`` is exempt; a real domain is not.
3. **``Content-Encoding: br`` for ``*.br``.**  Chunks and the snapshot are
   stored pre-compressed so the browser decompresses them and nothing we ship
   carries a decoder.  Optional in the sense that the page detects a
   non-decoding host and falls back — at 57 MiB instead of 11.5 MiB.

``sw.js`` MUST end up at the document root: it registers with ``scope: '/'``,
and a service worker cannot control paths above its own location.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
WEB = REPO / "web"

HTACCESS = """# Generated by scripts/wasm/stage-static.py

# 1. Cross-origin isolation. The emulator runs on pthreads and therefore needs
#    SharedArrayBuffer, which browsers grant only to an isolated page. Without
#    these two headers the page does not start.
<IfModule mod_headers.c>
  Header set Cross-Origin-Opener-Policy "same-origin"
  Header set Cross-Origin-Embedder-Policy "require-corp"
</IfModule>

# 2. WebAssembly MIME, in case the host predates it.
<IfModule mod_mime.c>
  AddType application/wasm .wasm
</IfModule>

# 3. Stored-Brotli artifacts. The NAND chunks and the snapshot are compressed at
#    build time; this declares the encoding so the BROWSER decompresses them.
#    Without it the page still works, by falling back to the uncompressed
#    snapshot -- 57 MiB instead of 11.5 MiB.
<IfModule mod_mime.c>
  AddEncoding br .br
</IfModule>
<FilesMatch "\\.br$">
  ForceType application/octet-stream
</FilesMatch>

# Content-addressed chunks never change under their name.
<FilesMatch "^[0-9a-f]{64}$">
  Header set Cache-Control "public, max-age=31536000, immutable"
</FilesMatch>
"""

NGINX = """# Generated by scripts/wasm/stage-static.py
#
# server { listen 443 ssl; root /var/www/iphone; ... }

# 1. Cross-origin isolation: pthreads -> SharedArrayBuffer -> isolated page.
add_header Cross-Origin-Opener-Policy  same-origin always;
add_header Cross-Origin-Embedder-Policy require-corp always;

types { application/wasm wasm; }

# 3. Stored-Brotli artifacts, served with the encoding declared. brotli_static
#    (ngx_brotli) also does this automatically for `foo` when `foo.br` exists.
location ~ \\.br$ {
    add_header Content-Encoding br always;
    add_header Cross-Origin-Opener-Policy  same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;
    default_type application/octet-stream;
}

# Content-addressed chunks never change under their name.
location ~ /chunks/[0-9a-f]{64}$ {
    add_header Cache-Control "public, max-age=31536000, immutable" always;
    add_header Content-Encoding br always;
    add_header Cross-Origin-Opener-Policy  same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;
    default_type application/octet-stream;
}
"""

README = """# Static deployment

Copy this directory to the document root and serve it over HTTPS:

    rsync -a --delete ./ user@host:/var/www/iphone/

Apache picks up `.htaccess` (needs `mod_headers`). For nginx, paste
`nginx.conf.snippet` into the server block -- note that `add_header` does NOT
inherit into a `location` that declares its own, which is why the isolation
headers are repeated there.

## Verify the deployment with two checks, not by loading the page

    curl -sI https://HOST/public/jit-boot/ | grep -i cross-origin
    curl -sI -H 'Accept-Encoding: br' https://HOST/{BR_SAMPLE} | grep -i content-encoding

The first must show both COOP and COEP; without them the emulator cannot start
and the failure looks like a broken build. The second must show
`Content-Encoding: br`; without it the page still works but pays {RAW_MIB} MiB
for the snapshot instead of {BR_MIB} MiB.

## What a visitor actually downloads

| | |
| --- | --- |
| instant boot (`?resume=1`) | ~{BR_MIB} MiB |
| cold boot from chunks | ~{PREFETCH_MIB} MiB |
| return visit | ~0 (Cache Storage) |

Total on disk here: {TOTAL_MIB} MiB.
"""


def copy(src: Path, dst: Path, report: list) -> None:
    """Copy, resolving symlinks. The dev tree symlinks the engine and firmware
    into build-wasm/ and m68ap-artifacts/, and an rsync without -L would ship
    dangling links."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dst, dirs_exist_ok=True, symlinks=False)
    else:
        shutil.copy2(src.resolve(), dst)
    report.append(dst)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build", required=True,
                    help="firmware build to stage, e.g. 1A543a")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--page", default="jit-boot",
                    help="which web/public/<page> to ship")
    ap.add_argument("--no-snapshot", action="store_true",
                    help="omit the instant-boot snapshot (cold boot only)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite a non-empty --out")
    args = ap.parse_args()

    page_src = WEB / "public" / args.page
    chunk_src = WEB / "chunked" / args.build
    if not page_src.is_dir():
        ap.error(f"no such page: {page_src}")
    if not chunk_src.is_dir():
        ap.error(f"no chunk set for {args.build}: {chunk_src}\n"
                 f"build one with scripts/wasm/chunk-pack.py")

    out = args.out
    if out.exists() and any(out.iterdir()) and not args.force:
        ap.error(f"{out} is not empty (use --force)")
    out.mkdir(parents=True, exist_ok=True)

    staged: list[Path] = []

    # The page and everything it fetches relatively. nand.pack is deliberately
    # NOT copied: the viewer streams chunks now, and it is 216 MiB of dead
    # weight that only web/bench-b/ still uses.
    for name in ("index.html", "qemu-system-arm.js", "qemu-system-arm.wasm",
                 "bootrom", "iboot.bin", "nor.bin"):
        src = page_src / name
        if not src.exists():
            print(f"missing: {src}", file=sys.stderr)
            return 1
        copy(src, out / "public" / args.page / name, staged)

    snap_src = page_src / "snapshots" / args.build
    have_snapshot = snap_src.is_dir() and not args.no_snapshot
    if have_snapshot:
        for f in snap_src.iterdir():
            # Ship state.br and the provenance; the raw state is the fallback
            # and doubles the upload, so include it only if there is no .br.
            if f.name == "state" and (snap_src / "state.br").exists():
                continue
            copy(f, out / "public" / args.page / "snapshots" / args.build / f.name,
                 staged)

    # Root-scoped: a service worker cannot control paths above itself.
    copy(WEB / "sw.js", out / "sw.js", staged)
    copy(WEB / "chunk-fetch-worker.js", out / "chunk-fetch-worker.js", staged)
    copy(WEB / "src", out / "src", staged)
    copy(chunk_src, out / "chunked" / args.build, staged)

    manifest = json.loads((chunk_src / "chunk-manifest.json").read_text())
    prefetch_mib = manifest.get("prefetchBytes", 0) / 1048576

    prov = snap_src / "state-provenance.json"
    br_mib = raw_mib = 0.0
    if have_snapshot and prov.exists():
        meta = json.loads(prov.read_text())
        br_mib = meta.get("brotli_bytes", 0) / 1048576
        raw_mib = meta.get("bytes", 0) / 1048576

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    br_sample = (f"public/{args.page}/snapshots/{args.build}/state.br"
                 if have_snapshot else
                 f"chunked/{args.build}/chunks/{manifest['hashes'][0]}")

    (out / ".htaccess").write_text(HTACCESS)
    (out / "nginx.conf.snippet").write_text(NGINX)
    (out / "README.md").write_text(
        README.replace("{BR_SAMPLE}", br_sample)
              .replace("{BR_MIB}", f"{br_mib:.1f}")
              .replace("{RAW_MIB}", f"{raw_mib:.1f}")
              .replace("{PREFETCH_MIB}", f"{prefetch_mib:.1f}")
              .replace("{TOTAL_MIB}", f"{total / 1048576:.0f}"))

    print(f"staged {len(staged)} entries into {out}")
    print(f"  on disk        {total / 1048576:8.1f} MiB")
    print(f"  cold boot      {prefetch_mib:8.1f} MiB downloaded")
    if have_snapshot:
        print(f"  instant boot   {br_mib:8.1f} MiB downloaded  (?resume=1)")
    else:
        print("  instant boot   not staged (no snapshot; "
              "scripts/wasm/build-snapshot.py)")
    print(f"\nserve over HTTPS with COOP/COEP; see {out}/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
