#!/bin/bash

set -euo pipefail

if [[ $# -lt 1 || $# -gt 3 ]]; then
    echo "usage: $0 QEMU_BINARY [APP_BUNDLE] [ipod-touch|iphone-2g]" >&2
    exit 2
fi

QEMU_BINARY="$1"
APP_BUNDLE="${2:-/Applications/iPod Touch.app}"
PROFILE="${3:-ipod-touch}"
CONTENTS="$APP_BUNDLE/Contents"
TARGET_BINARY="$CONTENTS/MacOS/qemu-system-arm"
TARGET_FRAMEWORKS="$CONTENTS/Frameworks"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

case "$PROFILE" in
    ipod-touch|iphone-2g) ;;
    *)
        echo "Invalid S5L8900 profile: $PROFILE" >&2
        exit 2
        ;;
esac

if [[ ! -x "$QEMU_BINARY" ]]; then
    echo "QEMU binary is not executable: $QEMU_BINARY" >&2
    exit 1
fi
if [[ ! -d "$TARGET_FRAMEWORKS" || ! -f "$CONTENTS/Info.plist" ]]; then
    echo "Invalid S5L8900 application bundle: $APP_BUNDLE" >&2
    exit 1
fi
for helper in ipod-app-launcher.sh ipod-http-bridge.py ipod-https-proxy.py \
        ipod_tls_common.py ipod-nand-restore-dns.py ipod-nand-trust-ca.py \
        pack-ipod-nand.py; do
    if [[ ! -f "$SCRIPT_DIR/$helper" ]]; then
        echo "Missing installer helper: $SCRIPT_DIR/$helper" >&2
        exit 1
    fi
done

case "$PROFILE" in
    ipod-touch) FIRMWARE_SUBDIR="ipod_files" ;;
    iphone-2g) FIRMWARE_SUBDIR="iphone_files" ;;
esac
SOURCE_NAND="$CONTENTS/Resources/$FIRMWARE_SUBDIR/nand"
NAND_INPUT="${S5L8900_INSTALL_NAND_SOURCE:-$SOURCE_NAND}"
if [[ ! -d "$NAND_INPUT" ]]; then
    echo "Firmware NAND not found: $NAND_INPUT" >&2
    exit 1
fi
HTTPS_STATE_DIR="${S5L8900_HTTPS_STATE_DIR:-$HOME/Library/Application Support/S5L8900 HTTPS Bridge/$PROFILE}"

BUNDLE_EXECUTABLE="$(/usr/libexec/PlistBuddy \
    -c 'Print :CFBundleExecutable' "$CONTENTS/Info.plist")"
if [[ -z "$BUNDLE_EXECUTABLE" || "$BUNDLE_EXECUTABLE" == */* ||
        "$BUNDLE_EXECUTABLE" == "qemu-system-arm" ]]; then
    echo "Invalid CFBundleExecutable for launcher installation: $BUNDLE_EXECUTABLE" >&2
    exit 1
fi
TARGET_LAUNCHER="$CONTENTS/MacOS/$BUNDLE_EXECUTABLE"

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/s5l8900-app-engine.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/Frameworks"
cp -R "$TARGET_FRAMEWORKS/." "$STAGE/Frameworks/"
cp "$QEMU_BINARY" "$STAGE/qemu-system-arm"
chmod 755 "$STAGE/qemu-system-arm"
# NOTE: do NOT run `codesign --remove-signature` here. A freshly linked binary
# on modern macOS carries a *linker-signed* ad-hoc signature; removing it
# leaves a hole in __LINKEDIT and install_name_tool then refuses the file with
# "link edit information does not fill the __LINKEDIT segment". Rewriting the
# load commands invalidates the signature by itself, and everything is
# re-signed at the end of this script, so stripping first is both unnecessary
# and harmful. (Diagnosed 2026-07-25 -- it broke engine installs outright.)

SEEN="$STAGE/seen-dylibs"
touch "$SEEN"

bundle_dependencies() {
    local binary="$1"
    local dylib name destination first_dependency_line

    first_dependency_line=1
    if [[ "$binary" == *.dylib ]]; then
        # A dylib's first load-command entry is its own install ID.
        first_dependency_line=2
    fi

    while IFS= read -r dylib; do
        [[ -n "$dylib" ]] || continue
        name="$(basename "$dylib")"
        destination="$STAGE/Frameworks/$name"

        if [[ ! -f "$destination" ]]; then
            cp "$dylib" "$destination"
            chmod 644 "$destination"
        fi

        install_name_tool -change "$dylib" \
            "@executable_path/../Frameworks/$name" "$binary"

        if ! grep -Fqx "$name" "$SEEN"; then
            echo "$name" >> "$SEEN"
            bundle_dependencies "$destination"
        fi
    done < <(otool -L "$binary" | \
        awk -v first="$first_dependency_line" 'NR > first { print $1 }' | \
        grep '^/opt/homebrew/' || true)
}

bundle_dependencies "$STAGE/qemu-system-arm"

if otool -L "$STAGE/qemu-system-arm" | grep -q '/opt/homebrew/'; then
    echo "The staged engine still contains Homebrew load paths" >&2
    exit 1
fi
for dylib in "$STAGE/Frameworks/"*.dylib; do
    if otool -L "$dylib" | awk 'NR > 2 { print $1 }' | \
            grep -q '^/opt/homebrew/'; then
        echo "The staged framework still contains Homebrew load paths: $dylib" >&2
        exit 1
    fi
    codesign --force -s - "$dylib"
done
codesign --force -s - "$STAGE/qemu-system-arm"

# Patch only a staged NAND.  The installed bundle is updated below after CA
# generation, DNS restoration, trust injection, fsck, and packing all succeed.
#
# N45AP only. The DNS restore and CA trust injection reconstruct the boot HFS
# volume assuming the iPod's SINGLE-partition device-dump layout; an M68AP
# NAND is GENERATED by build-m68ap-nand.py with the real iPhone two-partition
# layout (root + data), so the same reconstruction fails outright
# ("aucun systeme de fichiers montable" / no mountable filesystem). The M68AP
# bundle therefore ships its generated NAND unmodified; giving the iPhone the
# same HTTPS-bridge trust is separate, still-to-do work (see BUILD.md).
if [[ "$PROFILE" == "ipod-touch" ]]; then
    ditto "$NAND_INPUT" "$STAGE/nand"
    CA_PEM="$(python3 "$SCRIPT_DIR/ipod_tls_common.py" --state "$HTTPS_STATE_DIR")"
    CA_DER="$HTTPS_STATE_DIR/bridge-ca.der"
    if [[ ! -f "$CA_PEM" || ! -f "$CA_DER" ]]; then
        echo "HTTPS bridge CA generation failed" >&2
        exit 1
    fi
    python3 "$SCRIPT_DIR/ipod-nand-restore-dns.py" --nand "$STAGE/nand"
    python3 "$SCRIPT_DIR/ipod-nand-trust-ca.py" \
        --nand "$STAGE/nand" --ca-cert "$CA_DER"
    python3 "$SCRIPT_DIR/pack-ipod-nand.py" "$STAGE/nand"
fi

ditto "$STAGE/Frameworks" "$TARGET_FRAMEWORKS"
cp "$STAGE/qemu-system-arm" "$TARGET_BINARY"
chmod 755 "$TARGET_BINARY"
cp "$SCRIPT_DIR/ipod-http-bridge.py" "$CONTENTS/Resources/ipod-http-bridge.py"
chmod 644 "$CONTENTS/Resources/ipod-http-bridge.py"
cp "$SCRIPT_DIR/ipod-https-proxy.py" "$CONTENTS/Resources/ipod-https-proxy.py"
cp "$SCRIPT_DIR/ipod_tls_common.py" "$CONTENTS/Resources/ipod_tls_common.py"
chmod 644 "$CONTENTS/Resources/ipod-https-proxy.py" \
    "$CONTENTS/Resources/ipod_tls_common.py"
if [[ "$PROFILE" == "ipod-touch" ]]; then
    ditto "$STAGE/nand" "$SOURCE_NAND"
fi
cp "$SCRIPT_DIR/ipod-app-launcher.sh" "$TARGET_LAUNCHER"
chmod 755 "$TARGET_LAUNCHER"
printf '%s\n' "$PROFILE" > "$CONTENTS/Resources/s5l8900-profile"
codesign --force --deep -s - "$APP_BUNDLE"
codesign --verify --deep --strict "$APP_BUNDLE"

echo "Installed $("$TARGET_BINARY" --version | head -1) into $APP_BUNDLE"
